---
title: ""
format: 
  docx:
    reference-doc: "ref.docx"
bibliography: "misc/ref.bib"
csl: "misc/scientific-reports.csl"
editor_options: 
  chunk_output_type: console
execute: 
  echo: false
  warning: false
  error: false
---

# Response to Reviewers

## Overview

We thank the Reviewers for their valuable feedback and constructive comments up to this point, which have helped us to significantly improve the quality and clarity of our manuscript. Below, we provide a detailed response to the comments from reviewer 2.

## Reviewer 2

**Comment**: "A lot of determinism has been previously demonstrated, where the respiration is spontaneous, e.g. as in Physica A, 283, no. 3-4 (2000): 451-461; and Philos. Trans. R. Soc. A, 371, no. 1997 (2013): 20110622;"

**Response**: We appreciate the reviewer’s suggestion and acknowledge the importance of prior deterministic models in characterizing cardio-respiratory interactions. In response, we have included a discussion in our manuscript that situates our model within this deterministic framework, highlighting how logistic functions effectively capture structured, time-dependent fluctuations in RR intervals. We have also cited the suggested references to acknowledge their contributions to the field.

**Comment**: "Similarly, if a complementary approach is taken, then the fluctuations of the cardio-respiratory interactions have been studied also through a stochastic approach, eg. as in Eur. Phys. J. B, 65 (2008): 425-433"

**Response**: We recognize the significance of stochastic modeling in capturing the inherent variability of cardio-respiratory interactions. While our current model is primarily deterministic, it does account for inter-individual variability, which aligns with aspects of stochastic approaches. We have now included a reference to prior stochastic studies and briefly discussed how future extensions of our model could incorporate stochastic elements to enhance its adaptability in more variable physiological conditions.

**Comment**: "The authors could reflect also these important works, if they have further opportunity in the revision process."

**Response**: We appreciate the reviewer’s insightful suggestion. In response, we have revised the discussion section to include references to both deterministic and stochastic modeling approaches, clarifying how our work aligns with and builds upon these perspectives. We believe this addition strengthens the manuscript by providing a broader context for our modeling approach.
